// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type profileTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *profileTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("profiles").
func (v *profileTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *profileTableType) Columns() []string {
	return []string{"id", "first_name", "last_name", "avatar"}
}

// NewStruct makes a new struct for that view or table.
func (v *profileTableType) NewStruct() reform.Struct {
	return new(Profile)
}

// NewRecord makes a new record for that table.
func (v *profileTableType) NewRecord() reform.Record {
	return new(Profile)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *profileTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// ProfileTable represents profiles view or table in SQL database.
var ProfileTable = &profileTableType{
	s: parse.StructInfo{Type: "Profile", SQLSchema: "", SQLName: "profiles", Fields: []parse.FieldInfo{{Name: "ID", Type: "int32", Column: "id"}, {Name: "FirstName", Type: "string", Column: "first_name"}, {Name: "LastName", Type: "string", Column: "last_name"}, {Name: "Avatar", Type: "*string", Column: "avatar"}}, PKFieldIndex: 0},
	z: new(Profile).Values(),
}

// String returns a string representation of this struct or record.
func (s Profile) String() string {
	res := make([]string, 4)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "FirstName: " + reform.Inspect(s.FirstName, true)
	res[2] = "LastName: " + reform.Inspect(s.LastName, true)
	res[3] = "Avatar: " + reform.Inspect(s.Avatar, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Profile) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.FirstName,
		s.LastName,
		s.Avatar,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Profile) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.FirstName,
		&s.LastName,
		&s.Avatar,
	}
}

// View returns View object for that struct.
func (s *Profile) View() reform.View {
	return ProfileTable
}

// Table returns Table object for that record.
func (s *Profile) Table() reform.Table {
	return ProfileTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Profile) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Profile) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Profile) HasPK() bool {
	return s.ID != ProfileTable.z[ProfileTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Profile) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int32(i64)
	} else {
		s.ID = pk.(int32)
	}
}

// check interfaces
var (
	_ reform.View   = ProfileTable
	_ reform.Struct = (*Profile)(nil)
	_ reform.Table  = ProfileTable
	_ reform.Record = (*Profile)(nil)
	_ fmt.Stringer  = (*Profile)(nil)
)

func init() {
	parse.AssertUpToDate(&ProfileTable.s, new(Profile))
}
